spring.application.name=APIGateway

server.port=9500

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance-id:${random.value}}


spring.cloud.gateway.server.webflux.routes[0].id=UserManagement
spring.cloud.gateway.server.webflux.routes[0].uri=lb://UserManagement
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[1].id=ProductManagement
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ProductManagement
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**

spring.cloud.gateway.server.webflux.routes[2].id=OrderManagement
spring.cloud.gateway.server.webflux.routes[2].uri=lb://OrderManagement
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/orders/**

spring.cloud.gateway.server.webflux.routes[3].id=InventoryManagement
spring.cloud.gateway.server.webflux.routes[3].uri=lb://InventoryManagement
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/inventories/**

spring.cloud.gateway.server.webflux.routes[4].id=DeliveryManagement
spring.cloud.gateway.server.webflux.routes[4].uri=lb://DeliveryManagement
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/deliveries/**

